name: weather_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #General
  dio: 4.0.6
  flutter_bloc: 8.0.1
  get_it: 7.2.0
  injectable: 1.5.3
  intl_utils: 2.7.0
  intl: 0.17.0
  # geolocator: 9.0.2
  # geocoding: 2.0.5

  #UI
  cupertino_icons: 1.0.2
  flutter_screenutil: 5.5.3+2

  #Generators
  freezed: 2.1.0
  json_serializable: 6.3.1
  retrofit: 3.0.1+1
  json_annotation: 4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.2.0
  injectable_generator: 1.5.4
  retrofit_generator: 4.0.3
  flutter_launcher_icons: 0.10.0
  flutter_gen_runner: 4.3.0
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Strings
  output_dir: lib/generated/l10n/

flutter_gen:
  output: lib/generated/assets/
  integrations:
    flutter_svg: true
